name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [nuxt-papi, react-dedot, react-papi]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
      working-directory: ${{ matrix.directory }}
    
    - name: Build project
      run: bun run build
      working-directory: ${{ matrix.directory }}
